# Generated by Django 5.2.1 on 2025-05-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
